name: Mon Premier Pipeline PFE

# 1. QUAND ? (Le Déclencheur)
# Le robot se réveille quand on pousse du code sur la branche 'main'
on:
  push:
    branches: [ "main" ]

# 2. QUOI ? (Les Jobs)
jobs:
  dire-bonjour:
    # Le robot utilise un ordinateur Linux prêté par GitHub
    runs-on: ubuntu-latest

    steps:
      # Étape A : Le robot télécharge ton code
      - name: Récupération du code
        uses: actions/checkout@v3

      # Étape B : Le robot exécute une commande
      - name: Message de bienvenue
        run: echo "Bravo Zainab ! Le pipeline fonctionne et le code est sécurisé."

      # Étape C : Le robot liste les fichiers pour prouver qu'il les voit
      - name: Vérifier les fichiers
        run: ls -la
