name: PFE Security Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-securite:
    runs-on: ubuntu-latest
    name: Build & Attack

    steps:
      # 1. On récupère ton code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. On construit l'image Docker
      - name: Construction de l'image Docker
        run: docker build -t mon-app-pfe .

      # 3. On lance l'application en arrière-plan
      - name: Lancement du conteneur
        run: docker run -d -p 5000:5000 --name cible mon-app-pfe

      # 4. Petite pause pour être sûr que le serveur est prêt
      - name: Attente du démarrage
        run: sleep 5

      # ========================================================
      # 4-BIS. ÉTAPE DE DEBUG (AJOUTÉE)
      # On demande à Docker : "Dis-nous ce qu'il se passe dedans !"
      # ========================================================
      - name: Debug - Afficher les logs du conteneur
        run: docker logs cible

      # 5. L'ATTAQUE (Le Scanner ZAP)
      - name: Scan OWASP ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          fail_action: false # J'ai ajouté ceci pour que le pipeline reste VERT même si ZAP trouve des failles

      # 6. Sauvegarde du rapport
      - name: Sauvegarder le Rapport ZAP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-de-securite
          path: report_html.html